---
abstract: 'Draw a variety of characters using the Pango'
author:
  - 'MASUDA Yuta <yuta.cpan@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Cv-Pango
no_index:
  directory:
    - t
    - inc
requires:
  Cv: 0.26
  ExtUtils::ParseXS: 2.22
  ExtUtils::PkgConfig: 1.12
  Pango: 1.223
version: 0.27
